pisa.countries = as.data.frame(matrix(c(
	"ALB","Albania",
	"ARG","Argentina",
	"AUS","Australia",
	"AUT","Austria",
	"AZE","Azerbaijan",
	"BEL","Belgium",
	"BRA","Brazil",
	"BGR","Bulgaria",
	"CAN","Canada",
	"CHL","Chile",
	"TAP","Chinese Taipei",
	"COL","Colombia",
	"HRV","Croatia",
	"CZE","Czech Republic",
	"DNK","Denmark",
	"QAR","Dubai (UAE)",
	"EST","Estonia",
	"FIN","Finland",
	"FRA","France",
	"DEU","Germany",
	"GRC","Greece",
	"HKG","Hong Kong-China",
	"HUN","Hungary",
	"ISL","Iceland",
	"IDN","Indonesia",
	"IRL","Ireland",
	"ISR","Israel",
	"ITA","Italy",
	"JPN","Japan",
	"JOR","Jordan",
	"KAZ","Kazakhstan",
	"KOR","Korea",
	"KGZ","Kyrgyzstan",
	"LVA","Latvia",
	"LIE","Liechtenstein",
	"LTU","Lithuania",
	"LUX","Luxembourg",
	"MAC","Macao-China",
	"MEX","Mexico",
	"MNE","Montenegro",
	"NLD","Netherlands",
	"NZL","New Zealand",
	"NOR","Norway",
	"PAN","Panama",
	"PER","Peru",
	"POL","Poland",
	"PRT","Portugal",
	"QAT","Qatar",
	"ROU","Romania",
	"RUS","Russian Federation",
	"SRB","Serbia",
	"QCN","Shanghai-China",
	"SGP","Singapore",
	"SVK","Slovak Republic",
	"SVN","Slovenia",
	"ESP","Spain",
	"SWE","Sweden",
	"CHE","Switzerland",
	"THA","Thailand",
	"TTO","Trinidad and Tobago",
	"TUN","Tunisia",
	"TUR","Turkey",
	"GBR","United Kingdom",
	"USA","United States",
	"URY","Uruguay"
), ncol=2, byrow=TRUE))
names(pisa.countries) = c('CNT3', 'Country')
pisa.countries$CNT3 = as.character(pisa.countries$CNT3)
pisa.countries$Country = as.character(pisa.countries$Country)
